name: GitHub Release Workflow

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.read_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from VERSION file
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Tag release if VERSION changed
        run: |
          echo "🔖 Tagging release if VERSION changed..."
          TAG="v${{ steps.read_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping."
          else
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git tag "$TAG"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} "$TAG"
            echo "Tagged and pushed $TAG"
          fi

      - name: Create GitHub release if new tag created
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.read_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
